program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - Ada_FMDOpt
    - SGD_FMDOpt
    - Diag_Ada_FMDOpt
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 0
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  m:
    values:
    - 1
    - 2
    - 5
    - 10
    - 20
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
  dataset_name:
    values:
    - mfac 
  eta_schedule:
    values:
    - constant
    - stochastic
    - exponential
