program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - SGD_FMDOpt
    - SLS_FMDOpt
    - Ada_FMDOpt
  normalize_epochs_lengths:
    values:
    - 1
  outer_c:
    values:
    - 0.5
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 1
  label:
    values:
    - 'workshop-fig8'
  log_lr:
    values:
      - -4.
      - -3.
      - -2.
      - -1.
      -  0.
      -  1.
      -  2.
      -  3. 
  m:
    values:
    - 1
    - 5
    - 10
    - 20
  use_optimal_stepsize:
    values:
    - 0
  outer_c:
    values:
    - 0.5
  c:
    values:
    - 0.5
    - 0.1
    - 0.01
  loss:
    values:
    - CrossEntropyLoss
  dataset_name:
    values:
    - mnist
  eta_schedule:
    values:
    - constant
