program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD_FMDOpt
  episodes:
    values:
    - 100
  m:
    values:
    - 1
    - 2
    - 10
    - 20
  seed:
    values:
    - 1
    - 2
    - 3
  log_eta:
    values:
    - -3.
    - -2.
    - -1.
    - 0.0
    - 1.
    - 2.
    - 3.
  batch_size:
    values:
    # - 1
    - 25
    - 125
    - 625
  use_optimal_stepsize:
    values:
    - 0
  loss:
    values:
    - MSELoss
    # - CrossEntropyLoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    - stochastic
    - constant
  c:
    values:
    - 0.1
    # - 0.01
    # - 0.001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
