program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - LSOpt
    - SGD
    - Sadagrad
    - Adam
    - Adagrad
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 0
  batch_size:
    values:
    - 25
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
  c:
    values:
    - 0.5
  eta_schedule:
    values:
    - exponential
    - constant
    - stochastic
