program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  episodes:
    values:
    - 25000
  algo:
    values:
    - Ada_FMDOpt
  normalize_epochs_lengths:
    values:
    - 1
  m:
    values:
    - 1
    - 2
    - 5
    - 10
    - 20
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    - constant
  c:
    values:
    - 0.1 
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
