program: atari/atari_ex.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - OGD
    - AdaOGD
    - AdamOGD
    - OSLS
    - GULF2_OGD
  log_lr:
    values:
    - 2.
    - 1.
    - 0.
    - -1.
    - -2.
    - -3.
    - -4.
  label:
    values:
    - 'aistats-atari'
  env_name:
    values:
    - 'BreakoutNoFrameskip-4'
  use_optimal_stepsize:
    values:
    - 0
  c:
    values:
    - 0.5
  episodes:
    values:
    - 100
  samples_per_update:
    values:
    - 1000
  eta_schedule:
    values:
    - constant
