program: atari/atari_ex.py
entity: wilderlavington
method: grid
project: FunctionalOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SSO_SLS
    - SSO_OGD
  m:
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
  log_lr:
    values:
    - 0.
    - -1.
    - -2.
    - -3.
    - -4.
    - -5.
  label:
    values:
    - 'aistats-atari'
  env_name:
    values:
    - 'PongNoFrameskip-v4'
  use_optimal_stepsize:
    values:
    - 0
  outer_c:
    values:
    - 0.5
  beta:
    values:
    - 1.
  beta_update:
    values:
    - 0.
    - 1.
  c:
    values:
    - 0.5
    - 0.1
  episodes:
    values:
    - 100
  samples_per_update:
    values:
    - 500
  eta_schedule:
    values:
    - stochastic
