program: atari/atari_ex.py
entity: wilderlavington
method: grid
project: FunctionalOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SSO_OGD
  m:
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
  log_lr:
    values:
    - 2.
    - 1.
    - 0.
    - -1.
    - -2.
    - -3.
    - -4.
  label:
    values:
    - 'aistats-atari'
  use_optimal_stepsize:
    values:
    - 0
  c:
    values:
    - 0.5
    - 0.1
  episodes:
    values:
    - 25
  samples_per_update:
    values:
    - 1000
  eta_schedule:
    values:
    - constant
