program: atari/atari_ex.py
entity: wilderlavington
method: grid
project: FunctionalOptimizationFinal
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SSO_OGD
    - SSO_SLS
    - SSO_Sadagrad
  m:
    values:
    - 1
    - 10
    - 100
    - 1000
  log_lr:
    values:
    - 3.
    - 2.
    - 1.
    - 0.
    - -1.
    - -2.
    - -3.
  label:
    values:
    - 'aistats-atari'
  env_name:
    values:
    - 'BreakoutNoFrameskip-v4'
    - 'PongNoFrameskip-v4'
  use_optimal_stepsize:
    values:
    - 0
  beta:
    values:
    - 1.
    - 0.
  beta_update:
    values:
    - 1.
  c:
    values:
    - 0.5
  episodes:
    values:
    - 100
  samples_per_update:
    values:
    - 1000
    - 100
  eta_schedule:
    values:
    - constant
    - stochastic
