program: mujoco/mujoco_ex.py
entity: wilderlavington
method: grid
project: FunctionalOptimizationFinal
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - OGD
    - AdaOGD
    - AdamOGD
    - OSls
  log_lr:
    values:
    - -3.
    - -2.
    - -1.
    - 0.0
    - 1.
    - 2.
    - 3.
  model_type:
    values:
    - 'linear'
    - 'nn'
  env_name:
    values:
    - 'Hopper-v2'
    - 'Walker2d-v2'
  beta:
    values:
    - 1
    - 0
  beta_update:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3 
  label:
    values:
    - 'aistats-mujoco'
  episodes:
    values:
    - 50
  samples_per_update:
    values:
    - 1000
    - 100
  eta_schedule:
    values:
    - constant
