program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - GULF2
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 1
  label:
    values:
    - 'workshop-fig11'
  gulf2_prox_steps:
    values:
    - 1
    - 5
    - 10
    - 20
  gulf2_alpha:
    values:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
  eta_schedule:
    values:
    - constant
