entity: wilderlavington
method: grid
project: FunctionalOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD_FMDOpt
    - Ada_FMDOpt
  episodes:
    values:
    - 100
  m:
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
  batch_size:
    values:
    - 1
    - 10
    - 100
    - 500
  use_optimal_stepsize:
    values:
    - 1
    - 0
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
  eta_schedule:
    values:
    - stochastic
    - constant
    - exponential
  c:
    values:
    - 0.1
    - 0.01
    - 0.001
    - 0.0001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
  stoch_reg:
    values:
    - 0
    - 1
