program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  episodes:
    values:
    - 25000
  algo:
    values:
    - Sadagrad
    - SGD
  normalize_epochs_lengths:
    values:
    - 1
  use_optimal_stepsize:
    values:
    - 0
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  use_optimal_stepsize:
    values:
    - 0
  log_eta:
    values:
    - -3.
    - -2.
    - -1.
    - 0.
    - 1.
    - 2.
    - 3.
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    - constant
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
