program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD
    - Adam
    - Adagrad
  episodes:
    values:
    - 100
  batch_size:
    values:
    # - 1
    # - 10
    - 100
    # - 500
  use_optimal_stepsize:
    values:
    - 1
    # - 0
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
  eta_schedule:
    values:
    - stochastic
    - constant
    # - exponential
  dataset_name:
    values:
    - mushrooms
    - ijcnn
