program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD
    - Adam
    - Adagrad
    - LSOpt
  episodes:
    values:
    - 25000
  normalize_episode_lengths:
    values:
    - 1
  use_optimal_stepsize:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    - stochastic
    - constant
    - exponential
  c:
    values:
    - 0.1
    # - 0.01
    # - 0.001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
