program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  episodes:
    values:
    - 500
  algo:
    values:
    - SGD_FMDOpt
  episodes:
    values:
    - 200000
  normalize_episode_lengths:
    values:
    - 1
  use_optimal_stepsize:
    values:
    - 1
  m:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 1
    - 5
    - 10
    - 25
    - 100
    - 500
  use_optimal_stepsize:
    values:
    - 0
  log_eta:
    values:
    - 0.0
    - 1.
    - 2.
    - 3.
    - 5.
    - 10.
    - 20.
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    - stochastic
    - constant
    - exponential
  c:
    values:
    - 0.1
    # - 0.01
    # - 0.001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
