program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  episodes:
    values:
    - 500
  algo:
    values:
    - SGD_FMDOpt
    - SGD
    - Adam
    - AdaGrad
    - LSOpt
  episodes:
    values:
    - 100
  m:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 1
    - 5
    - 10
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    # - CrossEntropyLoss
    - BCEWithLogitsLoss
  eta_schedule:
    values:
    # - stochastic
    - constant
  c:
    values:
    - 0.1
    # - 0.01
    # - 0.001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
