program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD
    - Adam
    - Adagrad
  episodes:
    values:
    - 100
  seed:
    values:
    - 1
    - 2
    - 3
  log_eta:
    values:
    - -3.5
    - -2.5
    - -1.5
    - 0.0
    - 1.5
    - 2.5
    - 3.5
  batch_size:
    values:
    # - 1
    # - 10
    - 100
    # - 500
  use_optimal_stepsize:
    values:
    # - 1
    - 0
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
  eta_schedule:
    values:
    - stochastic
    - constant
    # - exponential
  dataset_name:
    values:
    - mushrooms
    - ijcnn
