program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  algo:
    values:
    - SGD_FMDOpt
  episodes:
    values:
    - 100
  m:
    values:
    - 1
    - 2
    - 10
    - 20
  batch_size:
    values:
    # - 1
    - 10
    # - 100
    - 500
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - CrossEntropyLoss
  eta_schedule:
    values:
    - stochastic
    - constant
  c:
    values:
    - 0.1
    - 0.01
    - 0.001
  dataset_name:
    values:
    - mushrooms
    - ijcnn
  stoch_reg:
    values:
    - 0
    - 1
