program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  episodes:
    values:
    - 25000
  algo:
    values:
    - SGD
    - Sadagrad
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  use_optimal_stepsize:
    values:
    - 1
  loss:
    values:
    - MSELoss
    - BCEWithLogitsLoss
  dataset_name:
    values:
    - mushrooms
    - ijcnn
    - rcv1
  eta_schedule:
    values:
    - constant
    - stochastic
    - exponential
