program: main.py
entity: wilderlavington
method: grid
project: FunctionalStochasticOptimization
metric:
  goal: minimize
  name: grad_norm
parameters:
  min_epochs:
    values:
    - 500
  algo:
    values:
    - LSOpt
    - SGD
    - Adam
    - Sadagrad
  normalize_epochs_lengths:
    values:
    - 1
  seed:
    values:
    - 1
    - 2
    - 3
  fullbatch:
    values:
    - 0
  batch_size:
    values:
    - 5
    - 25
    - 125
    - 625
  log_lr:
    values:
      - -3.
      - -2.
      - -1.
      -  0.
      -  1.
      -  2.
      -  3.
  label:
    values:
    - 'workshop-fig5'
  use_optimal_stepsize:
    values:
    - 0
  loss:
    values:
    - MSELoss
  dataset_name:
    values:
    - mfac
  c:
    values:
    - 0.5
  eta_schedule:
    values:
    - constant
